//
//  MoviesCollection.swift
//  MoviesList
//
//  Created by Ant Colony on 13. 11. 2021..
//

//func getImage() {}

import UIKit

enum MoviesCollection {
    static let movies: [Movie] = [
        Movie(name: "No Time To Dye",releaseYear: 2021,shortDesc: "A James Bond Movie",longDesc: "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.", image: UIImage(named: "noTimeToDie")!),
        Movie(name: "1922",releaseYear: 2017, shortDesc: "1922 is a 2017 American horror drama film", longDesc: "n 1922, Wilfred  James is a farmer living in Hemingford, Nebraska with his wife, Arlette, and their 14-year-old son, Henry. Wilf is strongly opposed to Arlette's plans to sell the farm and move to Omaha. He decides to convince Henry to help murder Arlette, holding Henry's girlfriend, Shannon, whose relationship Arlette opposes, at stake. Henry reluctantly agrees to assist his father in carrying out the murder. Wilf pretends to agree to the sale, appeasing Arlette. As she celebrates, she becomes inebriated. After Wilf carries her to bed in a drunken stupor, Henry covers her face while Wilf cuts her throat with a butcher's knife. Wilf dumps her body into a dry well where her corpse is soon fed upon by rats. The next day, they drop a cow into the well to hide Arlette's body and provide a reason for filling in the well. Sheriff Jones is suspicious following her sudden disappearance; he searches the house, but finds no proof of a crime, tentatively believing Wilf's story that his wife absconded.As time passes, Henry becomes brooding and isolated, regretting the crime that he and his father have committed. Shannon grows increasingly concerned and subsequently discovers she pregnant with Henry's child. Her parents decide to send her to a Catholic institution in Omaha until the baby is born and will then be given up for adoption. Henry steals Wilf's car, arrives in Omaha, and runs away with Shannon.", image: UIImage(named: "1922")!),
        Movie(name: "Dune",releaseYear: 2021,shortDesc: "Feature adaptation of Frank Herbert's science fiction novel", longDesc: "Feature adaptation of Frank Herbert's science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.", image: UIImage(named: "dune")!),
        Movie(name: "Fast and Furios 6",releaseYear: 2013,shortDesc: "Fast & Furious 6 (titled onscreen as Furious 6) is a 2013 American action film directed by Justin Lin and written by Chris Morgan.", longDesc: " It stars Vin Diesel, Paul Walker, Dwayne Johnson, Michelle Rodriguez, Jordana Brewster, Tyrese Gibson, Chris Ludacris Bridges, Sung Kang, Gal Gadot, Luke Evans, Gina Carano, and John Ortiz. In the film, Dominic Toretto, Brian O'Conner, and the team are offered amnesty for their past crimes in exchange for apprehending a mercenary organization, one member of which is Toretto's presumed deceased lover and wife, Letty Ortiz.After departing from the overt street racing theme of previous installments in Fast Five, development of Fast & Furious 6 continues this, featuring spy and adventure elements, in the hopes to increase the series' audience. Preparation for the film began in April 2011, with Diesel and Lin returning that June. Discussions arose filming alongside a potential seventh installment; these were abandoned once principal photography began in July 2012, which lasted until that December, with filming locations including Los Angeles, London, Glasgow, and the Canary Islands.Fast & Furious 6 premiered in London on May 17, 2013, and was theatrically released worldwide in conventional and IMAX theaters by Universal Pictures on May 24. The film received generally positive reviews from critics, with praise for the stunts and action sequences. It grossed $788.7 million worldwide, making it the sixth-highest-grossing film of 2013, the then-fourth highest grossing film distributed by Universal, and the then-highest grossing installment in the franchise. A sequel, Furious 7, was released in the United States on April 3, 2015.", image: UIImage(named: "ff")!),
        Movie(name: "Dark Knight Rises",releaseYear: 2012,shortDesc: "The final part of Nolans Batman adaptation", longDesc: "Feature adaptation of Frank Herbert's science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.", image: UIImage(named: "knightrises")!),
        Movie(name: "Mission: Impossible – Rogue Nation",releaseYear: 2014,shortDesc: "It is a 2015 American action spy film written and directed by Christopher McQuarrie",longDesc: "The film stars Tom Cruise, Jeremy Renner, Simon Pegg, Rebecca Ferguson, Ving Rhames, Alec Baldwin, Sean Harris, Simon McBurney, and Tom Hollander, with Cruise, Renner, Pegg, and Rhames reprising their roles from previous films. Rogue Nation is produced by Cruise, J. J. Abrams, and David Ellison of Skydance Productions. In the film, IMF (Impossible Missions Force) agent Ethan Hunt is on the run from the CIA, following the IMF's dissolution, as he tries to prove the existence of the Syndicate, a mysterious global freelance terrorist group composed of many former intelligence officers from many different countries and its 'ledger'.Filming began on August 21, 2014, in Vienna, Austria, and concluded on March 12, 2015. The film was released in North America by Paramount Pictures on July 31, 2015. It received positive reviews from critics and grossed $682 million worldwide, becoming the eighth-highest-grossing film of 2015 as well as the third-highest-grossing film starring Cruise.A sequel, Mission: Impossible – Fallout, was released on July 27, 2018 with McQuarrie returning as writer and director.", image: UIImage(named: "missionimpossible")!),
        Movie(name: "Iron Man",releaseYear: 2008,shortDesc: "The first installment of the Iron Man series",longDesc: "Iron Man is a 2008 American superhero film based on the Marvel Comics character of the same name. Produced by Marvel Studios and distributed by Paramount Pictures,[N 1] it is the first film in the Marvel Cinematic Universe (MCU). Directed by Jon Favreau from a screenplay by the writing teams of Mark Fergus and Hawk Ostby, and Art Marcum and Matt Holloway, the film stars Robert Downey Jr. as Tony Stark / Iron Man alongside Terrence Howard, Jeff Bridges, Shaun Toub, and Gwyneth Paltrow. In the film, following his escape from captivity by a terrorist group, world famous industrialist and master engineer Tony Stark builds a mechanized suit of armor and becomes the superhero Iron Man.", image: UIImage(named: "ironman")!),
        Movie(name: "Fist Full of Dollars",releaseYear: 1964,shortDesc: "One of the first Clin Eastwood Westerns",longDesc: "A Fistful of Dollars (Italian: Per un pugno di dollari, lit. 'For a Fistful of Dollars' titled on-screen as Fistful of Dollars) is a 1964 Spaghetti Western film directed by Sergio Leone and starring Clint Eastwood in his first leading role", image: UIImage(named: "fistfulofdollars")!),
        Movie(name: "Room",releaseYear: 2021,shortDesc: "Room is a drama film directed by Lenny Abrahamson and written by Emma Donoghue, based on her 2010 novel of the same name.",longDesc: "Room premiered at the Telluride Film Festival on September 4, 2015, and later screened at the 2015 Toronto International Film Festival, where it received the People's Choice Award. The film was theatrically released in Canada on October 23, 2015 by Elevation Pictures and in the United Kingdom and Ireland on January 15, 2016 by StudioCanal. It began a limited theatrical run in the United States on October 16, 2015 by A24. Room was acclaimed by critics, who lauded the performances of Larson and Tremblay and the storytelling, and grossed $36.3 million on a $13 million budget. Cited as one of the best films of the year, Room received numerous awards and nominations. At the 88th Academy Awards, Room received four nominations, including Best Picture. It also won nine Canadian Screen Awards, including Best Motion Picture, and seven Irish Film & Television Awards, including Best Film. Larson won the Academy Award, Golden Globe Award and the BAFTA Award.", image: UIImage(named: "room")!),
        Movie(name: "Thin Red Line",releaseYear: 2021,shortDesc: "It is a 1998 American epic war film written and directed by Terrence Malick.",longDesc: " It is the second screen adaptation of the 1962 novel of the same name by James Jones, following the 1964 film; however, this film is not considered a remake. Telling a fictionalized version of the Battle of Mount Austen, which was part of the Guadalcanal Campaign in the Pacific Theater of World War II, it portrays soldiers of C Company, 1st Battalion, 27th Infantry Regiment, 25th Infantry Division, played by Sean Penn, Jim Caviezel, Nick Nolte, Elias Koteas and Ben Chaplin. The novel's title alludes to a line from Rudyard Kipling's poem Tommy, from Barrack-Room Ballads, in which he calls British foot soldiers the thin red line of heroes,[3] referring to the stand of the 93rd Regiment in the Battle of Balaclava of the Crimean War.The film marked Malick's return to filmmaking after a 20-year absence. It co-stars Adrien Brody, George Clooney, John Cusack, Woody Harrelson, Jared Leto, John C. Reilly and John Travolta. Reportedly, the first assembled cut took seven months to edit and ran five hours. By the final cut, footage of performances by Bill Pullman, Lukas Haas, and Mickey Rourke had been removed (one of Rourke's scenes was included in the special features outtakes of the Criterion Blu-ray and DVD release). The film was scored by Hans Zimmer and shot by John Toll. Principal photography took place in Queensland, Australia and in the Solomon Islands.", image: UIImage(named: "thinredline")!),

    ]
}
